org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
kotlin.incremental=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.configureondemand=false
org.gradle.caching=true
