services:
  - type: web
    name: rehoboth-backend
    env: python
    region: frankfurt  # plus proche de l'Afrique (Europe)
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false  # à saisir manuellement depuis Supabase
      - key: CORS_ALLOWED_ORIGINS
        sync: false  # à saisir après avoir le domaine Vercel
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false  # ex: https://rehoboth-backend.onrender.com
      - key: FRONTEND_URL
        sync: false  # ex: https://rehoboth.vercel.app
