# Generated by Django 6.0.3 on 2026-04-17 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('demande_recue', 'Nouvelle demande reçue'), ('demande_acceptee', 'Demande acceptée'), ('demande_refusee', 'Demande refusée'), ('technicien_en_route', 'Technicien en route'), ('intervention_terminee', 'Intervention terminée'), ('paiement_recu', 'Paiement reçu'), ('retrait_effectue', 'Retrait effectué'), ('evaluation_recue', 'Évaluation reçue'), ('message_recu', 'Nouveau message'), ('compte_valide', 'Compte validé'), ('compte_rejete', 'Compte rejeté'), ('systeme', 'Notification système')], default='systeme', max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('objet_id', models.UUIDField(blank=True, null=True, verbose_name='ID objet lié')),
                ('objet_type', models.CharField(blank=True, max_length=50, verbose_name='Type objet lié')),
                ('lu', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
