# Generated by Django 6.0.3 on 2026-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP temporaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_session_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Jeton de challenge OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=True, verbose_name='Double authentification activée'),
        ),
    ]
