# Generated by Django 6.0.3 on 2026-04-17 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=100, verbose_name='Icône (emoji ou nom)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('0', 'Lundi'), ('1', 'Mardi'), ('2', 'Mercredi'), ('3', 'Jeudi'), ('4', 'Vendredi'), ('5', 'Samedi'), ('6', 'Dimanche')], max_length=1)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'disponibilites',
            },
        ),
        migrations.CreateModel(
            name='DocumentTechnicien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_doc', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('certificat', 'Certificat professionnel'), ('diplome', 'Diplôme'), ('autre', 'Autre document')], max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='documents/techniciens/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents_techniciens',
            },
        ),
        migrations.CreateModel(
            name='ProfilTechnicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=150, verbose_name='Spécialité')),
                ('description', models.TextField(blank=True, verbose_name='Description des services')),
                ('tarif_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zone_couverture', models.CharField(blank=True, max_length=200)),
                ('annees_experience', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nb_evaluations', models.IntegerField(default=0)),
                ('nb_missions', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniciens', to='techniciens.categorie', verbose_name='Catégorie de service')),
            ],
            options={
                'verbose_name': 'Profil Technicien',
                'verbose_name_plural': 'Profils Techniciens',
                'db_table': 'profils_techniciens',
            },
        ),
    ]
