# Generated by Django 6.0.3 on 2026-04-17 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniciens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profiltechnicien',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_technicien', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='documenttechnicien',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='techniciens.profiltechnicien', verbose_name='Technicien'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='techniciens.profiltechnicien'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together={('technicien', 'jour_semaine')},
        ),
    ]
