# Generated by Django 6.0.3 on 2026-04-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('adresse', models.CharField(max_length=300, verbose_name="Adresse d'intervention")),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude GPS')),
                ('type_intervention', models.CharField(choices=[('immediat', 'Immédiat (urgent)'), ('planifie', 'Planifié (date choisie)')], default='immediat', max_length=20)),
                ('mode', models.CharField(choices=[('sur_place', 'Sur place (déplacement)'), ('a_distance', 'À distance (téléphone/vidéo)')], default='sur_place', max_length=20)),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_route', 'Technicien en route'), ('en_cours', 'Intervention en cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('rapport', models.TextField(blank=True, verbose_name='Rapport du technicien')),
                ('montant_devis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du devis (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='demandes/photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photos_demandes',
            },
        ),
    ]
