# Generated by Django 6.0.3 on 2026-04-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('techniciens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techniciens.categorie', verbose_name='Catégorie de service'),
        ),
    ]
