# Generated by Django 6.0.3 on 2026-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name="Adresse d'intervention"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS'),
        ),
    ]
