# Generated by Django 6.0.3 on 2026-04-17 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0003_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Client payeur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='demandes.demande', verbose_name='Demande associée'),
        ),
        migrations.AddField(
            model_name='retrait',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
    ]
